version: "3.9"

services:
  db:
    image: postgres:15.1
    restart: always
    container_name: intergration-tests-timecheck
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timecheck
      POSTGRES_PASSWORD: timecheck
      POSTGRES_DB: timecheck
