version: "3.9"

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timecheck
      POSTGRES_PASSWORD: timecheck
      POSTGRES_DB: timecheck
    restart: always

  timecheck-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: timecheck-api-dev
    image: timecheck-api:0.1
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 5555:5555
    restart: always
